server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://wlsdnr4675.cwjff3qij1v0.ap-northeast-2.rds.amazonaws.com/wlsdnr4675?useSSLd=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: wlsdnr4675
    password: wlsdnr4675
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  jwt:
    secret: jwtSecret
UserController:
  signup: Creates user and returns its JWT token
  signin: Authenticates user and returns its JWT token
